name: quest

channels:
    - tpeulen
    - conda-forge

dependencies:
    - python =3.7
    - pyqt >=5.6.0
    - numpy
    - numexpr
    - guiqwt
    - pyopengl
    - pymol
    - labellib
    - pymol-open-source
