name: quest

channels:
    - conda-forge

dependencies:
    - python=3.7
    - pyyaml
    - numpy
    - numba
    - scipy
    - numexpr
    - pytables
    - hdf5
    - mdtraj
    - ipython
    - matplotlib
    - pyqt>=5.6.0
    - pyqtgraph
    - pyopengl
    - qtconsole
    - qsci_editor
