{% set name = "quest" %}
{% set version = "latest" %}

package:
  name: {{ name|lower }}
  version: {{ version|lower }}
  # version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: ..

build:
  number: {{ GIT_DESCRIBE_NUMBER|int }}
  string: np{{ CONDA_NPY }}py{{ CONDA_PY }}_{{ GIT_BUILD_STR }}
  entry_points:
    - quest=quest.quest_gui:start_gui

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python {{ python }}
    - setuptools
    - cython
    - numpy
  run:
    - python {{ python }}
    - numpy
    - numexpr
    - pyopengl
    - labellib
    - pyyaml
    - pyqt <2.0
    - pytables
    - guiqwt
    - guidata <=1.7.6 # broken guidata.qt in higher version
    - pymol-open-source
    - libstdcxx-ng # [linux]

about:
  home: https://github.com/Fluorescence-Tools/quest
  license: MIT
  license_file: LICENSE
  summary: QuEst is a protein structure based fluorescence quenching estimator
  description:
    QuEst is a structure based fluorescence quenching estimator that simulates dynamic
    quenching of fluorescence decays of dyes that are coupled to the surface of a proteins.
    Dynamic fluorescence quenching is simulated by modelling (i) the diffusion of the dye
    and (ii) the quenching of the dye by surface exposed aromatic amino-acids.

extra:
  recipe-maintainers:
    - tpeulen
